//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gibbed.DragonAge.SaveGenerator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gibbed.DragonAge.SaveGenerator.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connor freed.
        /// </summary>
        public static string ArlConnorResult_ConnorFreed {
            get {
                return ResourceManager.GetString("ArlConnorResult_ConnorFreed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isolde killed Connor.
        /// </summary>
        public static string ArlConnorResult_IsoldeKilledConnor {
            get {
                return ResourceManager.GetString("ArlConnorResult_IsoldeKilledConnor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player knocked out Isolde, killed Connor.
        /// </summary>
        public static string ArlConnorResult_IsoldeKnockedOutPCKilledConnor {
            get {
                return ResourceManager.GetString("ArlConnorResult_IsoldeKnockedOutPCKilledConnor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string ArlConnorResult_None {
            get {
                return ResourceManager.GetString("ArlConnorResult_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player killed Connor.
        /// </summary>
        public static string ArlConnorResult_PCKilledConnor {
            get {
                return ResourceManager.GetString("ArlConnorResult_PCKilledConnor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted the demon&apos;s offer.
        /// </summary>
        public static string ArlDemonResult_AcceptedOffer {
            get {
                return ResourceManager.GetString("ArlDemonResult_AcceptedOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intimidated the demon.
        /// </summary>
        public static string ArlDemonResult_Intimidated {
            get {
                return ResourceManager.GetString("ArlDemonResult_Intimidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Circle did the ritual.
        /// </summary>
        public static string ArlRitualResult_CircleDoesRitual {
            get {
                return ResourceManager.GetString("ArlRitualResult_CircleDoesRitual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jowan did the ritual.
        /// </summary>
        public static string ArlRitualResult_JowanDoesRitual {
            get {
                return ResourceManager.GetString("ArlRitualResult_JowanDoesRitual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string ArlRitualResult_None {
            get {
                return ResourceManager.GetString("ArlRitualResult_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refused to help.
        /// </summary>
        public static string ArlSiegeOptions_Abandoned {
            get {
                return ResourceManager.GetString("ArlSiegeOptions_Abandoned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siege is over.
        /// </summary>
        public static string ArlSiegeOptions_Over {
            get {
                return ResourceManager.GetString("ArlSiegeOptions_Over", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted the Architect&apos;s offer.
        /// </summary>
        public static string AwakeningArchitectResult_DealWithArchitect {
            get {
                return ResourceManager.GetString("AwakeningArchitectResult_DealWithArchitect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Killed the Architect.
        /// </summary>
        public static string AwakeningArchitectResult_KilledArchitect {
            get {
                return ResourceManager.GetString("AwakeningArchitectResult_KilledArchitect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string AwakeningArchitectResult_None {
            get {
                return ResourceManager.GetString("AwakeningArchitectResult_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defended the farms.
        /// </summary>
        public static string AwakeningDefenseResult_Farms {
            get {
                return ResourceManager.GetString("AwakeningDefenseResult_Farms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None / other.
        /// </summary>
        public static string AwakeningDefenseResult_None {
            get {
                return ResourceManager.GetString("AwakeningDefenseResult_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defended the trade routes.
        /// </summary>
        public static string AwakeningDefenseResult_Roads {
            get {
                return ResourceManager.GetString("AwakeningDefenseResult_Roads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amaranthine was saved.
        /// </summary>
        public static string AwakeningOptions_AmaranthineSaved {
            get {
                return ResourceManager.GetString("AwakeningOptions_AmaranthineSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anders died in the siege.
        /// </summary>
        public static string AwakeningOptions_AndersDiedInSiege {
            get {
                return ResourceManager.GetString("AwakeningOptions_AndersDiedInSiege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruited Anders.
        /// </summary>
        public static string AwakeningOptions_AndersRecruited {
            get {
                return ResourceManager.GetString("AwakeningOptions_AndersRecruited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained Silverite ore.
        /// </summary>
        public static string AwakeningOptions_HerrenCompletedSilverite {
            get {
                return ResourceManager.GetString("AwakeningOptions_HerrenCompletedSilverite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nathaniel died in the siege.
        /// </summary>
        public static string AwakeningOptions_NathanielDiedInSiege {
            get {
                return ResourceManager.GetString("AwakeningOptions_NathanielDiedInSiege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NATHANIEL_FRIENDLY_ELIGIBLE.
        /// </summary>
        public static string AwakeningOptions_NathanielFriendly {
            get {
                return ResourceManager.GetString("AwakeningOptions_NathanielFriendly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruited Nathaniel.
        /// </summary>
        public static string AwakeningOptions_NathanielRecruited {
            get {
                return ResourceManager.GetString("AwakeningOptions_NathanielRecruited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player is Orlesian Warden (not imported).
        /// </summary>
        public static string AwakeningOptions_Orlesian {
            get {
                return ResourceManager.GetString("AwakeningOptions_Orlesian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vigil&apos;s Keep siege completed.
        /// </summary>
        public static string AwakeningOptions_VigilsKeepSiegeCompleted {
            get {
                return ResourceManager.GetString("AwakeningOptions_VigilsKeepSiegeCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dwarf Commoner.
        /// </summary>
        public static string Background_Dwarf_Commoner {
            get {
                return ResourceManager.GetString("Background_Dwarf_Commoner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dwarf Noble.
        /// </summary>
        public static string Background_Dwarf_Noble {
            get {
                return ResourceManager.GetString("Background_Dwarf_Noble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City ELf.
        /// </summary>
        public static string Background_Elf_City {
            get {
                return ResourceManager.GetString("Background_Elf_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dalish Elf.
        /// </summary>
        public static string Background_Elf_Dalish {
            get {
                return ResourceManager.GetString("Background_Elf_Dalish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human Noble.
        /// </summary>
        public static string Background_Human_Noble {
            get {
                return ResourceManager.GetString("Background_Human_Noble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magi.
        /// </summary>
        public static string Background_Magi {
            get {
                return ResourceManager.GetString("Background_Magi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zathrian sacrified himself.
        /// </summary>
        public static string BeastOptions_ZathrianSacrified {
            get {
                return ResourceManager.GetString("BeastOptions_ZathrianSacrified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string BeastResult_None {
            get {
                return ResourceManager.GetString("BeastResult_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sided with the elves.
        /// </summary>
        public static string BeastResult_SidedWithElves {
            get {
                return ResourceManager.GetString("BeastResult_SidedWithElves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sided with the werewolves.
        /// </summary>
        public static string BeastResult_SidedWithWerewolves {
            get {
                return ResourceManager.GetString("BeastResult_SidedWithWerewolves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burned Cailan in a funeral pyre.
        /// </summary>
        public static string CailanResult_Burned {
            get {
                return ResourceManager.GetString("CailanResult_Burned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Cailan for the Darkspawn.
        /// </summary>
        public static string CailanResult_Darkspawn {
            get {
                return ResourceManager.GetString("CailanResult_Darkspawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unplayed.
        /// </summary>
        public static string CailanResult_None {
            get {
                return ResourceManager.GetString("CailanResult_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Cailan for the wolves.
        /// </summary>
        public static string CailanResult_Wolves {
            get {
                return ResourceManager.GetString("CailanResult_Wolves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sided with the Mages.
        /// </summary>
        public static string CircleResult_Mages {
            get {
                return ResourceManager.GetString("CircleResult_Mages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string CircleResult_None {
            get {
                return ResourceManager.GetString("CircleResult_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sided with the Templars.
        /// </summary>
        public static string CircleResult_Templars {
            get {
                return ResourceManager.GetString("CircleResult_Templars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mage.
        /// </summary>
        public static string Class_Mage {
            get {
                return ResourceManager.GetString("Class_Mage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rogue.
        /// </summary>
        public static string Class_Rogue {
            get {
                return ResourceManager.GetString("Class_Rogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warrior.
        /// </summary>
        public static string Class_Warrior {
            get {
                return ResourceManager.GetString("Class_Warrior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alistair killed the Archdemon.
        /// </summary>
        public static string ClimaxArchdemonResult_AlistairKilledArchdemon {
            get {
                return ResourceManager.GetString("ClimaxArchdemonResult_AlistairKilledArchdemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loghain killed the Archdemon.
        /// </summary>
        public static string ClimaxArchdemonResult_LoghainKilledArchdemon {
            get {
                return ResourceManager.GetString("ClimaxArchdemonResult_LoghainKilledArchdemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string ClimaxArchdemonResult_None {
            get {
                return ResourceManager.GetString("ClimaxArchdemonResult_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player killed the Archdemon.
        /// </summary>
        public static string ClimaxArchdemonResult_PlayerKilledArchdemon {
            get {
                return ResourceManager.GetString("ClimaxArchdemonResult_PlayerKilledArchdemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string ClimaxRitualResult_None {
            get {
                return ResourceManager.GetString("ClimaxRitualResult_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Alistair.
        /// </summary>
        public static string ClimaxRitualResult_RitualWithAlistair {
            get {
                return ResourceManager.GetString("ClimaxRitualResult_RitualWithAlistair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Loghain.
        /// </summary>
        public static string ClimaxRitualResult_RitualWithLoghain {
            get {
                return ResourceManager.GetString("ClimaxRitualResult_RitualWithLoghain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With the player.
        /// </summary>
        public static string ClimaxRitualResult_RitualWithPlayer {
            get {
                return ResourceManager.GetString("ClimaxRitualResult_RitualWithPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player named Chancellor.
        /// </summary>
        public static string EpilogueBoonResult_Chancellor {
            get {
                return ResourceManager.GetString("EpilogueBoonResult_Chancellor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mages of The Circle of Ferelden freed.
        /// </summary>
        public static string EpilogueBoonResult_Circle {
            get {
                return ResourceManager.GetString("EpilogueBoonResult_Circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dalish elves given their own land.
        /// </summary>
        public static string EpilogueBoonResult_Dalish {
            get {
                return ResourceManager.GetString("EpilogueBoonResult_Dalish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None / Other.
        /// </summary>
        public static string EpilogueBoonResult_None {
            get {
                return ResourceManager.GetString("EpilogueBoonResult_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruited Barkspawn.
        /// </summary>
        public static string FollowerOptions_DogRecruited {
            get {
                return ResourceManager.GetString("FollowerOptions_DogRecruited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruited Leliana.
        /// </summary>
        public static string FollowerOptions_LelianaRecruited {
            get {
                return ResourceManager.GetString("FollowerOptions_LelianaRecruited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruited Zevran.
        /// </summary>
        public static string FollowerOptions_ZevranRecruited {
            get {
                return ResourceManager.GetString("FollowerOptions_ZevranRecruited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Gender_Female {
            get {
                return ResourceManager.GetString("Gender_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Gender_Male {
            get {
                return ResourceManager.GetString("Gender_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Played.
        /// </summary>
        public static string GolemStarted {
            get {
                return ResourceManager.GetString("GolemStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threesome with Alistair.
        /// </summary>
        public static string IsabellaResult_IsabelaAndAlistairThreesome {
            get {
                return ResourceManager.GetString("IsabellaResult_IsabelaAndAlistairThreesome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threesome with Leliana.
        /// </summary>
        public static string IsabellaResult_IsabelaAndLelianaThreesome {
            get {
                return ResourceManager.GetString("IsabellaResult_IsabelaAndLelianaThreesome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threesome with Zevran.
        /// </summary>
        public static string IsabellaResult_IsabelaAndZevranThreesome {
            get {
                return ResourceManager.GetString("IsabellaResult_IsabelaAndZevranThreesome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foursome.
        /// </summary>
        public static string IsabellaResult_IsabelaInFoursome {
            get {
                return ResourceManager.GetString("IsabellaResult_IsabelaInFoursome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string IsabellaResult_None {
            get {
                return ResourceManager.GetString("IsabellaResult_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slept with Isabella.
        /// </summary>
        public static string IsabellaResult_SleptWith {
            get {
                return ResourceManager.GetString("IsabellaResult_SleptWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Killed Avernus.
        /// </summary>
        public static string KeepOptions_AvernusKilled {
            get {
                return ResourceManager.GetString("KeepOptions_AvernusKilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string KeepOptions_Completed {
            get {
                return ResourceManager.GetString("KeepOptions_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Killed Sophia.
        /// </summary>
        public static string KeepOptions_SophiaKilled {
            get {
                return ResourceManager.GetString("KeepOptions_SophiaKilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avernus doing bad experiments.
        /// </summary>
        public static string KeepResult_AvernusDoingBadExperiments {
            get {
                return ResourceManager.GetString("KeepResult_AvernusDoingBadExperiments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avernus doing good experiments.
        /// </summary>
        public static string KeepResult_AvernusDoingGoodExperiments {
            get {
                return ResourceManager.GetString("KeepResult_AvernusDoingGoodExperiments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string KeepResult_None {
            get {
                return ResourceManager.GetString("KeepResult_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left the party and become a wandering drunk.
        /// </summary>
        public static string LandsmeetAlistairResult_Drunkard {
            get {
                return ResourceManager.GetString("LandsmeetAlistairResult_Drunkard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was executed by Anora.
        /// </summary>
        public static string LandsmeetAlistairResult_Executed {
            get {
                return ResourceManager.GetString("LandsmeetAlistairResult_Executed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crowned king / remained a warden.
        /// </summary>
        public static string LandsmeetAlistairResult_None {
            get {
                return ResourceManager.GetString("LandsmeetAlistairResult_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alistair rules jointly with Anora.
        /// </summary>
        public static string LandsmeetKingResult_AlistairEngagedToAnora {
            get {
                return ResourceManager.GetString("LandsmeetKingResult_AlistairEngagedToAnora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alistair rules with the player.
        /// </summary>
        public static string LandsmeetKingResult_AlistairEngagedToPlayer {
            get {
                return ResourceManager.GetString("LandsmeetKingResult_AlistairEngagedToPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alistair rules.
        /// </summary>
        public static string LandsmeetKingResult_AlistairIsKing {
            get {
                return ResourceManager.GetString("LandsmeetKingResult_AlistairIsKing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anora rules.
        /// </summary>
        public static string LandsmeetKingResult_AnoraIsQueen {
            get {
                return ResourceManager.GetString("LandsmeetKingResult_AnoraIsQueen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string LandsmeetKingResult_None {
            get {
                return ResourceManager.GetString("LandsmeetKingResult_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player rules.
        /// </summary>
        public static string LandsmeetKingResult_PlayerIsKing {
            get {
                return ResourceManager.GetString("LandsmeetKingResult_PlayerIsKing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was executed by Alistair.
        /// </summary>
        public static string LandsmeetLoghainResult_Executed {
            get {
                return ResourceManager.GetString("LandsmeetLoghainResult_Executed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string LandsmeetLoghainResult_None {
            get {
                return ResourceManager.GetString("LandsmeetLoghainResult_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruited into the Grey Wardens.
        /// </summary>
        public static string LandsmeetLoghainResult_Warden {
            get {
                return ResourceManager.GetString("LandsmeetLoghainResult_Warden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted, killed Leliana.
        /// </summary>
        public static string LelianaResult_Killed {
            get {
                return ResourceManager.GetString("LelianaResult_Killed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted, Leliana left party.
        /// </summary>
        public static string LelianaResult_LeftForever {
            get {
                return ResourceManager.GetString("LelianaResult_LeftForever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refused.
        /// </summary>
        public static string LelianaResult_None {
            get {
                return ResourceManager.GetString("LelianaResult_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gibbed&apos;s Dragon Age Save Generator.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. The Arl of Redcliffe.
        /// </summary>
        public static string PageDisplayName_Arl {
            get {
                return ResourceManager.GetString("PageDisplayName_Arl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12. Awakening.
        /// </summary>
        public static string PageDisplayName_Awakening {
            get {
                return ResourceManager.GetString("PageDisplayName_Awakening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Nature of the Beast.
        /// </summary>
        public static string PageDisplayName_Beast {
            get {
                return ResourceManager.GetString("PageDisplayName_Beast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Broken Circle.
        /// </summary>
        public static string PageDisplayName_Circle {
            get {
                return ResourceManager.GetString("PageDisplayName_Circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8. The Battle of Denerim.
        /// </summary>
        public static string PageDisplayName_Climax {
            get {
                return ResourceManager.GetString("PageDisplayName_Climax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10. Companions.
        /// </summary>
        public static string PageDisplayName_Companion {
            get {
                return ResourceManager.GetString("PageDisplayName_Companion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11. Downloadable Content.
        /// </summary>
        public static string PageDisplayName_DLC {
            get {
                return ResourceManager.GetString("PageDisplayName_DLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9. Epilogue.
        /// </summary>
        public static string PageDisplayName_Epilogue {
            get {
                return ResourceManager.GetString("PageDisplayName_Epilogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7. The Landsmeet.
        /// </summary>
        public static string PageDisplayName_Landsmeet {
            get {
                return ResourceManager.GetString("PageDisplayName_Landsmeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6. A Paragon of Her Kind.
        /// </summary>
        public static string PageDisplayName_Paragon {
            get {
                return ResourceManager.GetString("PageDisplayName_Paragon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Player.
        /// </summary>
        public static string PageDisplayName_Player {
            get {
                return ResourceManager.GetString("PageDisplayName_Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13. Summary.
        /// </summary>
        public static string PageDisplayName_Summary {
            get {
                return ResourceManager.GetString("PageDisplayName_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. The Urn of Sacred Ashes.
        /// </summary>
        public static string PageDisplayName_Urn {
            get {
                return ResourceManager.GetString("PageDisplayName_Urn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branka lived.
        /// </summary>
        public static string ParagonAnvilResult_BrankaAlive {
            get {
                return ResourceManager.GetString("ParagonAnvilResult_BrankaAlive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branka commit suicide.
        /// </summary>
        public static string ParagonAnvilResult_BrankaSuicided {
            get {
                return ResourceManager.GetString("ParagonAnvilResult_BrankaSuicided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caridin commit suicide.
        /// </summary>
        public static string ParagonAnvilResult_Caridin {
            get {
                return ResourceManager.GetString("ParagonAnvilResult_Caridin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string ParagonAnvilResult_None {
            get {
                return ResourceManager.GetString("ParagonAnvilResult_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bhelen.
        /// </summary>
        public static string ParagonKingResult_KingIsBhelen {
            get {
                return ResourceManager.GetString("ParagonKingResult_KingIsBhelen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harrowmont.
        /// </summary>
        public static string ParagonKingResult_KingIsHarrowmont {
            get {
                return ResourceManager.GetString("ParagonKingResult_KingIsHarrowmont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string ParagonKingResult_None {
            get {
                return ResourceManager.GetString("ParagonKingResult_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dwarf.
        /// </summary>
        public static string Race_Dwarf {
            get {
                return ResourceManager.GetString("Race_Dwarf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elf.
        /// </summary>
        public static string Race_Elf {
            get {
                return ResourceManager.GetString("Race_Elf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human.
        /// </summary>
        public static string Race_Human {
            get {
                return ResourceManager.GetString("Race_Human", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made love with Alistair.
        /// </summary>
        public static string RomanceOptions_AlistairLove {
            get {
                return ResourceManager.GetString("RomanceOptions_AlistairLove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romanced Alistair.
        /// </summary>
        public static string RomanceOptions_AlistairRomance {
            get {
                return ResourceManager.GetString("RomanceOptions_AlistairRomance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made love with Leliana.
        /// </summary>
        public static string RomanceOptions_LelianaLove {
            get {
                return ResourceManager.GetString("RomanceOptions_LelianaLove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romanced Leliana.
        /// </summary>
        public static string RomanceOptions_LelianaRomance {
            get {
                return ResourceManager.GetString("RomanceOptions_LelianaRomance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made love with Morrigan.
        /// </summary>
        public static string RomanceOptions_MorriganLove {
            get {
                return ResourceManager.GetString("RomanceOptions_MorriganLove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romanced Morrigan.
        /// </summary>
        public static string RomanceOptions_MorriganRomance {
            get {
                return ResourceManager.GetString("RomanceOptions_MorriganRomance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made love with Zevran.
        /// </summary>
        public static string RomanceOptions_ZevranLove {
            get {
                return ResourceManager.GetString("RomanceOptions_ZevranLove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romanced Zevran.
        /// </summary>
        public static string RomanceOptions_ZevranRomance {
            get {
                return ResourceManager.GetString("RomanceOptions_ZevranRomance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Killed Shale.
        /// </summary>
        public static string ShaleResult_Killed {
            get {
                return ResourceManager.GetString("ShaleResult_Killed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shale left party.
        /// </summary>
        public static string ShaleResult_Left {
            get {
                return ResourceManager.GetString("ShaleResult_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unplayed.
        /// </summary>
        public static string ShaleResult_None {
            get {
                return ResourceManager.GetString("ShaleResult_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruited Shale.
        /// </summary>
        public static string ShaleResult_Recruited {
            get {
                return ResourceManager.GetString("ShaleResult_Recruited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brother Genitivi returned to his home in Denerim.
        /// </summary>
        public static string UrnOptions_GenitiviReturnedToDenerim {
            get {
                return ResourceManager.GetString("UrnOptions_GenitiviReturnedToDenerim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Followed.
        /// </summary>
        public static string WitchResult_Followed {
            get {
                return ResourceManager.GetString("WitchResult_Followed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string WitchResult_Left {
            get {
                return ResourceManager.GetString("WitchResult_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string WitchResult_None {
            get {
                return ResourceManager.GetString("WitchResult_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stabbed.
        /// </summary>
        public static string WitchResult_Stabbed {
            get {
                return ResourceManager.GetString("WitchResult_Stabbed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string WizardView_Button_Cancel {
            get {
                return ResourceManager.GetString("WizardView_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string WizardView_Button_Finish {
            get {
                return ResourceManager.GetString("WizardView_Button_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next &gt;.
        /// </summary>
        public static string WizardView_Button_MoveNext {
            get {
                return ResourceManager.GetString("WizardView_Button_MoveNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Back.
        /// </summary>
        public static string WizardView_Button_MovePrevious {
            get {
                return ResourceManager.GetString("WizardView_Button_MovePrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragon Age.
        /// </summary>
        public static string WizardView_Header_Steps {
            get {
                return ResourceManager.GetString("WizardView_Header_Steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betrayed the player.
        /// </summary>
        public static string ZevranResult_GoesHostile {
            get {
                return ResourceManager.GetString("ZevranResult_GoesHostile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Killed before introduction.
        /// </summary>
        public static string ZevranResult_KilledBeforeIntroduction {
            get {
                return ResourceManager.GetString("ZevranResult_KilledBeforeIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left party after kissing farewell.
        /// </summary>
        public static string ZevranResult_LeavesAfterKissingFarewell {
            get {
                return ResourceManager.GetString("ZevranResult_LeavesAfterKissingFarewell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left party for good.
        /// </summary>
        public static string ZevranResult_LeavesForGood {
            get {
                return ResourceManager.GetString("ZevranResult_LeavesForGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string ZevranResult_None {
            get {
                return ResourceManager.GetString("ZevranResult_None", resourceCulture);
            }
        }
    }
}
